### ISSUE TITLE
Improve this Quiz-App.

### ISSUE THREAD

**Issue by JagjiwanChimkar** [JagjiwanChimkar/QuizApp#1]

**Comment by felipedferreira** [comment]
I would like to contribute please!

**Comment by parikshitghosh3** [comment]
add the hacktober fest label in this repo

**Comment by JagjiwanChimkar** [comment]
@parikshitghosh3  can you change those images because of change UI.

**Comment by parikshitghosh3** [comment]
> @parikshitghosh3 can you change those images because of change UI.

sure let me check

**Comment by harsh1206** [comment]
i made a pull request please check, it was my first :)

**Comment by JDOG787** [comment]
Hi I would like to style this a bit more if you don't mind! I also might improve a few other things.

**Comment by kbansal77** [comment]
I would like to contribute in this project.
